version: '3.8'

services:
  jenkins:
    image: my-jenkins-controller
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
